Add compatibility with Stairs, Moreblocks
minetest-mods/moreores pull request #27
Opened 2017-08-23 14:39 UTC by Jat15

Update sound.

2017-08-23 14:54 UTC, DS-Minetest commented
You should write here to first comment `Fixes #13.`, then it will be closed automatically by the merger on merge.
Code looks good.

2017-08-23 17:39 UTC, Jat15 commented
@DS-Minetest written in commentary.

2019-06-20 09:19 UTC, thomasrudin commented
Any progress on this? Looks like a simple addition... :confused:

2019-09-20 04:28 UTC, Panquesito7 commented on locale/es.txt
> +%s Block Slab =
```suggestion
%s Block Slab = Losa de bloque de %s
```

2019-09-20 04:28 UTC, Panquesito7 commented on locale/es.txt
> +%s Block Stair =
```suggestion
%s Block Stair = Escalera de bloque de %s
```

2020-02-14 09:36 UTC, louisroyer requested changes
Also, you should rebase on master HEAD and translations you added should be moved into `*.tr` files (with some syntax changes).

2020-02-14 09:36 UTC, louisroyer commented on init.lua
> +			stairs.register_stair_and_slab(
When minetest/minetest_game/pull/2584 will be merged, `desc_stair_outer` and `desc_stair_inner` parameters could be added (with translations for `@1 Outer Stair` and `@1 Inner Stair` in `locale` directory)

2020-02-14 09:36 UTC, louisroyer commented on locale/fr.txt
> +%s Block Slab = Demi-dalle en %s
```suggestion
%s Block Slab = Dalle en %s
```
to be consistent with others slabs defined in `stairs` mod.

2020-02-14 09:36 UTC, louisroyer commented on locale/fr.txt
> +%s Block Stair = Escaliers en %s
```suggestion
%s Block Stair = Escalier en %s
```
to be consistent with others stairs defined in `stairs`mod.

2020-02-14 09:36 UTC, louisroyer commented on depends.txt
> +moreblocks?
Replace lines 3 and 4 by
```
optional_depends = moreblocks, stairs
```
in `mod.conf`

2020-02-14 09:36 UTC, louisroyer commented on init.lua
> +				S("%s Block Stair"):format(S(description)),
```suggestion
				S("@1 Block Stair", S(description)),
```

2020-02-14 09:36 UTC, louisroyer commented on init.lua
> +				S("%s Block Slab"):format(S(description)),
```suggestion
				S("@1 Block Slab", S(description)),
```

2020-12-28 02:02 UTC, Panquesito7 approved these changes
Didn't test; looks good, though. I believe [More Ores](https://github.com/minetest-mods/moreores) should be updated, too.

2022-08-28 12:26 UTC, GreenDirkfried commented
I tested this in my own fork (https://github.com/GreenDirkfried/moreores/pull/5/files) and got undefined nodes.
I started a world with the "stairs" mod included and then only added the "moreblocks" mod afterwards, which leads to the old stairs being now undefined.
Can you confirm this problem?
I guess there should be an alias included.

2023-01-30 13:33 UTC, closed without merging